server:
  port: 8888
  #context-path: /cxy-admin
spring:
  thymeleaf:
    cache: true
    mode: LEGACYHTML5 #对没有结束符的HTML5标签解析出错的解决办法 LEGACYHTML5需要搭配一个额外的库NekoHTML才可用
    #prefix: classpath:/templates/login/ #可以自己新建文件夹指定模板所在路径
    #suffix: .login
  devtools:
    restart:
      enabled: true #开启热部署
      #additional-paths: src/main/java #监听的目录
     # exclude:  /static/**,/templates/** # 排除目录
      #trigger-file: .trigger # 触发文件，只有在改文件修改时才触发重启
   # livereload:
     # enabled: false #禁止自动刷新
    #remote:
     # secret: myappsecret #远程开发

#如果你只想打开一两个端点，那就先禁用全部端点，然后启用那几个你要的
endpoints:
  enabled: false
  beans:
    enabled: true
    id: mybeans #修改 Actuator的 beans的默认路径
  shutdown:
    enabled: true  #禁止shutdown





